// <auto-generated />
namespace Beat.Data.Migrations.Beat
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "202009281945206_add Event"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
